version: '3.8'

services:
  webapi:
    build: 
      dockerfile: ./Dockerfile
    container_name: webapi
    working_dir: /app
    ports:
      - "5277:80"
    environment:
      ASPNETCORE_ENVIRONMENT: "ConnectionStrings:Dbconnect = postgresql://localhost/${DB_NAME}?user=${DB_USER}&password=${DB_PASSWORD}" 


  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"