version: '3.8'

services:
  webapi:
    build: 
      dockerfile: ./Dockerfile
    container_name: webapi
    working_dir: /app
    depends_on:
      - postgres
    ports:
      - "80:8080"
    command: ["dotnet", "ef", "database update"]
    environment:
      ASPNETCORE_ENVIRONMENT: "ConnectionStrings:Dbconnect = postgresql://localhost/${DB_NAME}?user=${DB_USER}&password=${DB_PASSWORD}"
    networks:
      - dbNetwork 


  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - dbNetwork 

networks:
  dbNetwork:
